#! /bin/bash

# mainboard-gnuplot is part of the RoseWheel project.
# Copyright (C) 2011 RoseWheel Team <rosewheel@googlegroups.com>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.



if [ $# -lt 1 ]; then
    echo "usage: $0 /dev/ttyFD [bufsize]" >&2
    exit 1
fi

fd=$1

bufsize=100
if [ $# -gt 1 ]; then
    bufsize=$2
fi

stty -F $fd speed 115200 -parenb -cstopb
cat $fd | ./driveGnuPlots.pl               \
    4 $bufsize $bufsize $bufsize $bufsize  \
    -90 90                                 \
    -1000 1000                             \
    -24 24                                 \
    -24 24

exit 0
