LIB = libglobal.a

# One of "ram" or "flash"
MODE = flash

# One of "hd" or "md"
DENSITY = hd

# Object files
LIBOBJS = linalg.o strutils.o interpreter.o

# Uncomment to allow debugging
# CFLAGS += -DDEBUG

include ../Makefile.inc
